/**
 * Product RAG — compact dossiers from system_a_catalog used to ground the
 * positioning script generated by workflow-diagnosis. Read-only.
 *
 * Source of truth: public.system_a_catalog (description, extra_data with
 * benefits / technical_specifications / faq, technical_specs,
 * clinical_indications, compatibility_list, contraindications).
 */
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

type SupabaseClient = ReturnType<typeof createClient>;

export interface ProductDossier {
  name: string;
  category: string | null;
  subcategory: string | null;
  summary: string;            // short description (≤600 chars)
  benefits: string[];         // top 5
  specs: Array<{ label: string; value: string }>; // top 6
  faq: Array<{ q: string; a: string }>;           // top 3
  indications: string[];      // top 3
  compatibility: string[];    // top 3
  contraindications: string[]; // top 3
}

const CACHE = new Map<string, { exp: number; value: ProductDossier | null }>();
const TTL_MS = 5 * 60 * 1000;

const norm = (s: unknown) =>
  String(s ?? "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[®©™]/g, "")
    .replace(/[^\w\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();

function truncate(s: string, n: number): string {
  if (!s) return "";
  if (s.length <= n) return s;
  return s.slice(0, n - 1).trimEnd() + "…";
}

function buildDossier(row: any): ProductDossier {
  const extra = row?.extra_data ?? {};
  const benefits = Array.isArray(extra?.benefits) ? extra.benefits : [];
  const specs = Array.isArray(extra?.technical_specifications)
    ? extra.technical_specifications
    : Array.isArray(row?.technical_specs)
      ? row.technical_specs
      : [];
  const faq = Array.isArray(extra?.faq) ? extra.faq : [];
  return {
    name: String(row?.name || ""),
    category: row?.product_category || row?.category || null,
    subcategory: row?.product_subcategory || null,
    summary: truncate(String(row?.description || extra?.sales_pitch || ""), 600),
    benefits: benefits.slice(0, 5).map((b: any) => String(b)).filter(Boolean),
    specs: specs.slice(0, 6)
      .map((s: any) => ({ label: String(s?.label || s?.key || ""), value: String(s?.value || "") }))
      .filter((s: any) => s.label && s.value),
    faq: faq.slice(0, 3)
      .map((f: any) => ({ q: String(f?.question || ""), a: truncate(String(f?.answer || ""), 200) }))
      .filter((f: any) => f.q && f.a),
    indications: (Array.isArray(row?.clinical_indications) ? row.clinical_indications : []).slice(0, 3).map(String),
    compatibility: (Array.isArray(row?.compatibility_list) ? row.compatibility_list : []).slice(0, 3).map(String),
    contraindications: (Array.isArray(row?.contraindications) ? row.contraindications : []).slice(0, 3).map(String),
  };
}

async function fetchByMatch(
  supabase: SupabaseClient,
  label: string,
): Promise<any | null> {
  const cleaned = label.replace(/[®©™]/g, "").trim();
  if (!cleaned) return null;

  // 1) exact ilike on name
  let r = await supabase
    .from("system_a_catalog")
    .select("name, slug, product_category, product_subcategory, description, extra_data, technical_specs, clinical_indications, compatibility_list, contraindications, keywords")
    .eq("active", true)
    .ilike("name", cleaned)
    .limit(1)
    .maybeSingle();
  if (r.data) return r.data;

  // 2) ilike with wildcards
  r = await supabase
    .from("system_a_catalog")
    .select("name, slug, product_category, product_subcategory, description, extra_data, technical_specs, clinical_indications, compatibility_list, contraindications, keywords")
    .eq("active", true)
    .ilike("name", `%${cleaned}%`)
    .limit(1)
    .maybeSingle();
  if (r.data) return r.data;

  // 3) token-based fallback (≥2 significant tokens)
  const tokens = norm(cleaned).split(/\s+/).filter(t => t.length >= 4);
  if (tokens.length === 0) return null;

  const { data } = await supabase
    .from("system_a_catalog")
    .select("name, slug, product_category, product_subcategory, description, extra_data, technical_specs, clinical_indications, compatibility_list, contraindications, keywords")
    .eq("active", true)
    .or(tokens.map(t => `name.ilike.%${t}%,slug.ilike.%${t}%`).join(","))
    .limit(20);
  if (!data || data.length === 0) return null;

  // pick the row with the most token hits in name
  let best: any = null;
  let bestScore = 0;
  for (const row of data) {
    const n = norm(row.name);
    const score = tokens.reduce((a, t) => a + (n.includes(t) ? 1 : 0), 0);
    if (score > bestScore) { bestScore = score; best = row; }
  }
  return bestScore >= 1 ? best : null;
}

export async function fetchProductDossier(
  supabase: SupabaseClient,
  label: string | null | undefined,
): Promise<ProductDossier | null> {
  const key = norm(label);
  if (!key) return null;
  const cached = CACHE.get(key);
  if (cached && cached.exp > Date.now()) return cached.value;
  try {
    const row = await fetchByMatch(supabase, String(label));
    const dossier = row ? buildDossier(row) : null;
    CACHE.set(key, { exp: Date.now() + TTL_MS, value: dossier });
    return dossier;
  } catch (e) {
    console.warn("[product-rag] fetchProductDossier failed:", e);
    return null;
  }
}

export async function fetchRayshapeDossier(supabase: SupabaseClient): Promise<ProductDossier | null> {
  return fetchProductDossier(supabase, "Rayshape");
}

/** Render a dossier as compact text block to inject into an LLM prompt. */
export function renderDossierForPrompt(d: ProductDossier | null, header: string): string {
  if (!d) return "";
  const out: string[] = [`### ${header}: ${d.name}`];
  if (d.category) out.push(`Categoria: ${d.category}${d.subcategory ? ` / ${d.subcategory}` : ""}`);
  if (d.summary) out.push(`Descrição: ${d.summary}`);
  if (d.benefits.length) out.push(`Benefícios: ${d.benefits.join("; ")}`);
  if (d.specs.length) out.push(`Specs: ${d.specs.map(s => `${s.label}=${s.value}`).join("; ")}`);
  if (d.indications.length) out.push(`Indicações: ${d.indications.join("; ")}`);
  if (d.compatibility.length) out.push(`Compatibilidade: ${d.compatibility.join("; ")}`);
  if (d.contraindications.length) out.push(`Contraindicações: ${d.contraindications.join("; ")}`);
  if (d.faq.length) out.push(`FAQ: ${d.faq.map(f => `P:${f.q} R:${f.a}`).join(" | ")}`);
  return out.join("\n");
}

export function firstSentence(s: string | null | undefined): string {
  if (!s) return "";
  const m = String(s).match(/^[^.!?\n]{10,240}[.!?]/);
  return (m ? m[0] : String(s).slice(0, 200)).trim();
}