// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/query-leads.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.57.0";
import { z } from "npm:zod@^3.25.76";
var query_leads_default = defineTool({
  name: "query_leads",
  title: "Consultar leads",
  description: "Busca leads can\xF4nicos no CDP (lia_attendances, merged_into IS NULL). Filtros por nome, email, telefone, UF e etapa.",
  inputSchema: {
    nome: z.string().optional().describe("Filtro parcial por nome"),
    email: z.string().optional().describe("Filtro parcial por email"),
    telefone: z.string().optional().describe("Filtro parcial por telefone"),
    uf: z.string().length(2).optional().describe("UF de 2 letras"),
    etapa_funil: z.string().optional().describe("Etapa do funil CRM"),
    limit: z.number().int().min(1).max(50).optional().describe("Max resultados (padr\xE3o 20)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ nome, email, telefone, uf, etapa_funil, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("lia_attendances").select(
      "id, nome, email, telefone, cidade, uf, etapa_funil, responsavel, produto_interesse, intelligence_score, temperatura, real_status, total_deals_won, ltv_total, updated_at"
    ).is("merged_into", null).order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (nome) q = q.ilike("nome", `%${nome}%`);
    if (email) q = q.ilike("email", `%${email}%`);
    if (telefone) q = q.ilike("telefone", `%${telefone}%`);
    if (uf) q = q.eq("uf", uf.toUpperCase());
    if (etapa_funil) q = q.eq("etapa_funil", etapa_funil);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Erro: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify({ count: data?.length ?? 0, leads: data }, null, 2) }],
      structuredContent: { count: data?.length ?? 0, leads: data }
    };
  }
});

// src/lib/mcp/tools/search-knowledge.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.57.0";
import { z as z2 } from "npm:zod@^3.25.76";
var search_knowledge_default = defineTool2({
  name: "search_knowledge",
  title: "Buscar conte\xFAdo",
  description: "Pesquisa artigos publicados na base de conhecimento (knowledge_base) por t\xEDtulo, categoria e idioma.",
  inputSchema: {
    query: z2.string().optional().describe("Termo de busca no t\xEDtulo"),
    category: z2.string().optional().describe("Categoria (A-G)"),
    language: z2.enum(["pt", "en", "es"]).optional().describe("Idioma"),
    limit: z2.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, language, limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("knowledge_base").select("id, title, slug, category, language, status, meta_description, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (query) q = q.ilike("title", `%${query}%`);
    if (category) q = q.eq("category", category);
    if (language) q = q.eq("language", language);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Erro: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify({ count: data?.length ?? 0, articles: data }, null, 2) }],
      structuredContent: { count: data?.length ?? 0, articles: data }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "smartdent-revenue-os-mcp",
  title: "SmartDent Revenue OS",
  version: "0.1.0",
  instructions: "Tools de leitura sobre o CDP SmartDent. Use `query_leads` para consultar leads can\xF4nicos e `search_knowledge` para achar artigos publicados.",
  tools: [query_leads_default, search_knowledge_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
