CREATE TABLE public.edge_function_catalog (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  function_name text UNIQUE NOT NULL,
  category text NOT NULL,
  summary text NOT NULL,
  trigger_type text NOT NULL DEFAULT 'http',
  is_critical boolean NOT NULL DEFAULT false,
  deprecated boolean NOT NULL DEFAULT false,
  docs_url text,
  invocations_24h integer DEFAULT 0,
  errors_24h integer DEFAULT 0,
  avg_latency_ms integer,
  last_invocation_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.edge_function_catalog TO authenticated;
GRANT ALL ON public.edge_function_catalog TO service_role;
ALTER TABLE public.edge_function_catalog ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated read catalog" ON public.edge_function_catalog FOR SELECT TO authenticated USING (true);
CREATE POLICY "Service role manage catalog" ON public.edge_function_catalog FOR ALL TO service_role USING (true) WITH CHECK (true);

INSERT INTO public.edge_function_catalog (function_name, category, summary, trigger_type, is_critical) VALUES
  ('ai-content-formatter','IA Conteúdo','Formatador HTML/Markdown via IA','http',false),
  ('ai-enrich-pdf-content','IA Conteúdo','Enriquece PDF com IA','http',false),
  ('ai-generate-og-image','IA Conteúdo','Gera imagem OG','http',false),
  ('ai-metadata-generator','IA Conteúdo','Gera metadados SEO','http',false),
  ('ai-orchestrate-content','IA Conteúdo','Orquestra geração de conteúdo','http',false),
  ('archive-daily-chats','Admin','Arquiva chats diários','cron',false),
  ('astron-member-lookup','Astron','Lookup de membro Astron','http',false),
  ('astron-postback','Webhooks','Postback Astron Academy','webhook',false),
  ('audit-vitality-protocol','IA Conteúdo','Auditoria de protocolos alucinados','cron',false),
  ('auto-inject-product-cards','IA Conteúdo','Injeta cards de produto em artigos','http',false),
  ('automacoes-lia','CRM / Dra. LIA','Automações LIA (regras)','cron',false),
  ('backfill-deal-proposals','Backfills','Job de backfill (manual)','http',false),
  ('backfill-deals-append','Backfills','Job de backfill (manual)','http',false),
  ('backfill-hits-granular','Backfills','Job de backfill (manual)','http',false),
  ('backfill-intelligence-score','Backfills','Job de backfill (manual)','http',false),
  ('backfill-keywords','Backfills','Job de backfill (manual)','http',false),
  ('backfill-lia-leads','Backfills','Job de backfill (manual)','http',false),
  ('backfill-ltv','Backfills','Job de backfill (manual)','http',false),
  ('backfill-primary-deal','Backfills','Job de backfill (manual)','http',false),
  ('backfill-stranded-won-deals','Backfills','Job de backfill (manual)','http',false),
  ('batch-cognitive-analysis','CRM / Dra. LIA','Batch análise cognitiva','cron',false),
  ('cognitive-lead-analysis','CRM / Dra. LIA','Análise cognitiva por lead','http',false),
  ('copilot-draft-knowledge-article','Copilot','Ação Copilot KB','http',false),
  ('copilot-ingest-method-doc','Copilot','Ação Copilot KB','http',false),
  ('copilot-publish-knowledge-article','Copilot','Ação Copilot KB','http',false),
  ('create-technical-ticket','Suporte','Cria ticket técnico','http',false),
  ('create-test-articles','Backfills','Cria artigos teste','http',false),
  ('create-user','Admin','Cria usuário','http',false),
  ('data-export','Admin','Export de dados','http',false),
  ('document-proxy','PDF / Docs','Proxy de download de documento','http',false),
  ('dra-lia-export','CRM / Dra. LIA','Export conversas Dra. LIA','http',false),
  ('dra-lia-whatsapp','CRM / Dra. LIA','Dra. LIA via WhatsApp','http',true),
  ('dra-lia','CRM / Dra. LIA','Endpoint chat Dra. LIA (web)','http',true),
  ('enrich-article-seo','IA Conteúdo','Enriquece artigo (SEO)','http',false),
  ('enrich-resins-from-apostila','IA Conteúdo','Enriquece resinas a partir de apostila','http',false),
  ('enrichment-safety-net-cron','Saúde / Watchdog','Safety net para enrichment','cron',true),
  ('evaluate-interaction','Admin','Avalia interação','http',false),
  ('event-generate-about','Eventos','Gera about de evento','http',false),
  ('event-generate-image','Eventos','Gera imagem de evento','http',false),
  ('event-web-research','Eventos','Pesquisa web para evento','http',false),
  ('export-apostila-docx','PDF / Docs','Exporta apostila .docx','http',false),
  ('export-leads-full','Admin','Export completo de leads','http',false),
  ('export-parametros-ia','PDF / Docs','Exporta parâmetros IA','http',false),
  ('export-processing-instructions','PDF / Docs','Exporta instruções','http',false),
  ('extract-and-cache-pdf','PDF / Docs','Extrai e cacheia PDF','http',false),
  ('extract-commercial-expertise','PDF / Docs','Extrai expertise comercial','http',false),
  ('extract-pdf-raw','PDF / Docs','Extrai texto cru de PDF','http',false),
  ('extract-pdf-specialized','PDF / Docs','Extrator especializado de PDF','http',false),
  ('extract-pdf-text','PDF / Docs','Extrai texto de PDF','http',false),
  ('extract-video-content','PDF / Docs','Extrai conteúdo de vídeo','http',false),
  ('fix-category-e-cleanup','Backfills','Correção pontual','http',false),
  ('fix-corrupted-links','Backfills','Correção pontual','http',false),
  ('fix-piperun-links','PipeRun','Corrige links PipeRun','http',false),
  ('flow-executor','Admin','Executor de fluxos','http',false),
  ('format-processing-instructions','IA Conteúdo','Formata instruções de processamento','http',false),
  ('generate-certificate','PDF / Docs','Gera certificado','http',false),
  ('generate-documents-sitemap','SEO','Sitemap documentos','cron',false),
  ('generate-knowledge-sitemap-en','SEO','Sitemap KB EN','cron',false),
  ('generate-knowledge-sitemap-es','SEO','Sitemap KB ES','cron',false),
  ('generate-knowledge-sitemap','SEO','Sitemap KB PT','cron',false),
  ('generate-parameter-pages','SEO','Gera páginas de parâmetros','http',false),
  ('generate-sitemap','SEO','Gera sitemap principal','cron',false),
  ('generate-veredict-data','IA Conteúdo','Gera dados de veredicto','http',false),
  ('get-product-data','Admin','Busca dados de produto','http',false),
  ('google-oauth-callback','Google','OAuth callback Google','http',true),
  ('google-reviews-pull','Google','Pull manual de reviews','http',false),
  ('google-reviews-respond','Google','Responde review automaticamente','http',false),
  ('heal-knowledge-gaps','IA Conteúdo','Trata lacunas de KB','cron',false),
  ('import-astron-csv','Astron','Import CSV Astron','http',false),
  ('import-leads-csv','Backfills','Import manual','http',false),
  ('import-loja-integrada','E-commerce','Import pedidos Loja Integrada','http',false),
  ('import-proposals-csv','Backfills','Import manual','http',false),
  ('import-system-a-json','Backfills','Import manual','http',false),
  ('index-embeddings','SEO','Indexa embeddings','cron',false),
  ('index-spin-entries','SEO','Indexa SPIN entries','cron',false),
  ('ingest-knowledge-text','IA Conteúdo','Ingest de texto KB','http',false),
  ('knowledge-feed','SEO','Feed KB','http',false),
  ('link-videos-to-articles','IA Conteúdo','Linka vídeos a artigos','cron',false),
  ('llms-full-txt','SEO','Serve llms-full.txt','http',false),
  ('llms-txt','SEO','Serve llms.txt','http',false),
  ('manychat-lia-bridge','Webhooks','Bridge ManyChat → Dra. LIA','webhook',false),
  ('mcp-server','Copilot','MCP server','http',false),
  ('migrate-catalog-images','Backfills','Migração de dados','http',false),
  ('omie-api-explorer','Omie ERP','Explorador da API Omie','http',false),
  ('omie-lead-enricher','Omie ERP','Enriquece lead com dados Omie','cron',true),
  ('pandavideo-test','PandaVideo','Teste PandaVideo','http',false),
  ('pipeline-funnel-data','Admin','Dados do funil','http',false),
  ('piperun-api-test','PipeRun','Teste de API PipeRun','http',false),
  ('piperun-deal-diag','PipeRun','Diagnóstico de deal','http',false),
  ('piperun-full-sync','PipeRun','Sync completo PipeRun','http',false),
  ('piperun-offline-enrich','PipeRun','Enrich offline de cache PipeRun','cron',false),
  ('piperun-person-contact-backfill','PipeRun','Backfill contatos da person','http',false),
  ('piperun-person-empty-sweeper','PipeRun','Limpa persons vazias','cron',false),
  ('poll-loja-integrada-orders','Webhooks','Polling de pedidos Loja Integrada','cron',true),
  ('public-distributor-register','Distribuidores','Registro público de distribuidor','http',false),
  ('reformat-article-html','IA Conteúdo','Reformat HTML de artigo','http',false),
  ('register-loja-webhooks','Webhooks','Registra webhooks na Loja Integrada','http',false),
  ('resubmit-sitemap-to-gsc','Google','Resubmit sitemap no GSC','cron',false),
  ('rss-feed','SEO','RSS feed','http',false),
  ('sentinela-analyzer','Sentinela','Pipeline Sentinela WA','cron',false),
  ('sentinela-daily-report','Sentinela','Pipeline Sentinela WA','cron',false),
  ('sentinela-webhook-receiver','Webhooks','Receiver Sentinela WA','webhook',false),
  ('seo-llms-txt','SEO','Serve llms.txt dinâmico','http',false),
  ('seo-proxy','SEO','Proxy SSR para bots','http',true),
  ('sequence-runner','Admin','Runner de sequência','cron',false),
  ('setup-distributor-bucket','Distribuidores','Setup do bucket de distribuidor','http',false),
  ('smart-ops-backfill-equipment-from-deals','Backfills','Backfill SmartOps (manual)','http',false),
  ('smart-ops-backfill-person-origin','Backfills','Backfill SmartOps (manual)','http',false),
  ('smart-ops-backfill-pessoa-piperun-id','Backfills','Backfill SmartOps (manual)','http',false),
  ('smart-ops-copilot','Copilot','Copilot Senior Manager (chat)','http',true),
  ('smart-ops-cs-processor','Saúde / Watchdog','Processa CS Onboarding','cron',false),
  ('smart-ops-csv-audit-backfill','Backfills','Audit + backfill CSV','http',false),
  ('smart-ops-deal-form-note','PipeRun','Cria nota de form no deal','http',false),
  ('smart-ops-ecommerce-webhook','Webhooks','Webhook pedidos Loja Integrada','webhook',true),
  ('smart-ops-generate-card-descriptions','Admin','Gera descrições de cards','http',false),
  ('smart-ops-ingest-asset-from-a','Admin','Ingest asset do Sistema A','http',false),
  ('smart-ops-ingest-lead','Webhooks','Ingestão central de leads (Meta/Forms/Sellflux)','webhook',true),
  ('smart-ops-integration-check','Saúde / Watchdog','Health-check de integrações','cron',true),
  ('smart-ops-kanban-move','Admin','Move card no kanban','http',false),
  ('smart-ops-leads-api','Admin','API leads SmartOps','http',true),
  ('smart-ops-lia-assign','CRM / Dra. LIA','Roteamento de leads + Golden Rule + criação de deal','http',true),
  ('smart-ops-meta-ads-insights','Admin','Integração Meta Ads','http',false),
  ('smart-ops-meta-ads-manager','Admin','Integração Meta Ads','http',false),
  ('smart-ops-meta-csv-backfill','Backfills','Backfill CSV Meta','http',false),
  ('smart-ops-meta-lead-webhook','Webhooks','Webhook leadgen do Meta Ads','webhook',true),
  ('smart-ops-piperun-backfill-customfields','PipeRun','Backfill custom_fields PipeRun','http',false),
  ('smart-ops-piperun-detach-wrong-person','PipeRun','Desanexa person incorreta de deal','http',false),
  ('smart-ops-piperun-funnel-reconciler','PipeRun','Reconcilia funil/etapa PipeRun','cron',false),
  ('smart-ops-piperun-preflight','PipeRun','Preflight validação antes de criar deal','http',false),
  ('smart-ops-piperun-retry-failed-leads','PipeRun','Retry de leads falhos no PipeRun','cron',false),
  ('smart-ops-piperun-webhook','Webhooks','Webhook PipeRun (deal/person events)','webhook',true),
  ('smart-ops-preview-seller-note','PipeRun','Preview da nota do vendedor','http',false),
  ('smart-ops-proactive-outreach','Saúde / Watchdog','Outreach proativo','cron',false),
  ('smart-ops-reassign-danilo-vendas','Backfills','Reassign Danilo VENDAS','http',false),
  ('smart-ops-refresh-system-a-cache','Admin','Refresh cache Sistema A','cron',false),
  ('smart-ops-restore-vendas-snapshot','Backfills','Restaura snapshot VENDAS','http',false),
  ('smart-ops-revert-auto-trigger','Backfills','Reverte auto-trigger','http',false),
  ('smart-ops-sellflux-sync','Sellflux','Sync canônico Sellflux','cron',true),
  ('smart-ops-sellflux-webhook','Webhooks','Postback Sellflux','webhook',true),
  ('smart-ops-send-waleads','WhatsApp','Envio via WaLeads/Evolution','http',false),
  ('smart-ops-sms-disparopro','SMS','Disparo SMS DisparoPro','http',false),
  ('smart-ops-stagnant-processor','Saúde / Watchdog','Processa leads estagnados','cron',false),
  ('smart-ops-sync-piperun','PipeRun','Sync canônico para PipeRun','http',true),
  ('smart-ops-tldv-sync','tldv','Pipeline tldv','cron',false),
  ('smart-ops-tldv-webhook','Webhooks','Webhook reuniões tldv','webhook',false),
  ('smart-ops-wa-inbox-webhook','Webhooks','Webhook mensagens WhatsApp recebidas','webhook',true),
  ('smartops-gerar-comprovante-imersao','PDF / Docs','Comprovante de imersão','http',false),
  ('smartops-gerar-crachas-turma','PDF / Docs','Gera crachás de turma','http',false),
  ('smartops-gerar-doc-turma','PDF / Docs','Gera doc de turma','http',false),
  ('smartops-public-enrollment','Cursos','Inscrição pública em turma','http',true),
  ('smartops-public-nps','Cursos','NPS público de turma','http',false),
  ('smartops-send-course-reminder','Cursos','Envia lembrete de curso','cron',false),
  ('social-caption-generator','Social','Gera caption com IA','http',false),
  ('social-generate-image','Social','Gera imagem social','http',false),
  ('social-knowledge-fetch','Social','Busca KB para social','http',false),
  ('social-publish-worker','Social','Worker de publicação social','cron',true),
  ('sync-astron-members','Astron','Sync membros Astron','cron',false),
  ('sync-content-from-a','Admin','Sync conteúdo do Sistema A','cron',false),
  ('sync-google-drive-kb','Google','Sync KB do Google Drive','cron',false),
  ('sync-google-reviews','Google','Pull periódico de avaliações Google','cron',false),
  ('sync-knowledge-base','Admin','Sync KB','cron',false),
  ('sync-loja-integrada-clients','E-commerce','Sync clientes Loja Integrada','cron',false),
  ('sync-pandavideo','PandaVideo','Sync vídeos PandaVideo','cron',false),
  ('sync-sistema-a','Admin','Sync Sistema A','cron',false),
  ('sync-video-analytics','PandaVideo','Sync analytics de vídeo','cron',false),
  ('system-watchdog-deepseek','Saúde / Watchdog','Watchdog IA com DeepSeek','cron',true),
  ('test-api-viewer','Copilot','Viewer API debug','http',false),
  ('training-create-drive-folder','Cursos','Cria pasta Drive da turma','http',false),
  ('training-factory-carousel','Training Factory','Pipeline geração de treinamento','http',false),
  ('training-factory-generate-image','Training Factory','Pipeline geração de treinamento','http',false),
  ('training-factory-publish','Training Factory','Pipeline geração de treinamento','http',false),
  ('training-factory-render','Training Factory','Pipeline geração de treinamento','http',false),
  ('training-factory-trigger','Training Factory','Pipeline geração de treinamento','http',false),
  ('translate-card-row','IA Conteúdo','Tradução de card','http',false),
  ('translate-content','IA Conteúdo','Tradução de conteúdo','http',false),
  ('verify-distributor-backlink','Distribuidores','Verifica backlink','cron',false),
  ('video-sitemap','SEO','Sitemap dinâmico de vídeos','http',false),
  ('wa-ai-preview','WhatsApp','Preview IA de mensagem','http',false),
  ('wa-broadcast-dispatch','WhatsApp','Broadcast 1-para-N','cron',false),
  ('wa-campaign-builder','WhatsApp','Builder de campanhas WA','http',false),
  ('wa-contact-sync-cron','WhatsApp','Cron sync de contatos','cron',false),
  ('wa-delivery-reconciler','WhatsApp','Reconciliação de entrega','cron',false),
  ('wa-dispatcher','WhatsApp','Despachador da fila WA','cron',true),
  ('wa-group-blast','WhatsApp','Disparo de mensagens para grupos','http',true),
  ('wa-sync-groups','WhatsApp','Sincroniza grupos das instâncias','http',false),
  ('wa-verify-lead','WhatsApp','Verifica existência do número','http',false),
  ('zernio-accounts-sync','Social','Sync contas Zernio','cron',false),
  ('zernio-broadcast-dispatch','Social','Dispatch broadcast Zernio','cron',false),
  ('zernio-contacts-sync','Social','Sync contatos Zernio','cron',false),
  ('zernio-metrics-sync','Social','Sync métricas Zernio','cron',false),
  ('zernio-webhook','Webhooks','Webhook Zernio (IG/FB)','webhook',false);

UPDATE public.system_integration_registry
SET label = 'Lovable AI Gateway — DeepSeek (ping)',
    notes = 'DeepSeek descontinuado no gateway; ping feito via google/gemini-2.5-flash'
WHERE key = 'api_lovable_ai_deepseek';