
-- 1) Limpar produtos atuais
DELETE FROM public.workflow_cell_mappings WHERE mapping_type = 'product';

-- 2) Inserir lista canônica
INSERT INTO public.workflow_cell_mappings (workflow_stage, workflow_cell, mapping_type, mapped_value, mapped_label) VALUES
-- Etapa 1 · Captura Digital
('etapa_1_scanner','scanner_intraoral','product','Scanner Intraoral MEDIT i500','Scanner Intraoral MEDIT i500'),
('etapa_1_scanner','scanner_intraoral','product','Scanner Intraoral MEDIT i600','Scanner Intraoral MEDIT i600'),
('etapa_1_scanner','scanner_intraoral','product','Scanner Intraoral MEDIT i700','Scanner Intraoral MEDIT i700'),
('etapa_1_scanner','scanner_intraoral','product','Scanner Intraoral MEDIT i700 Wireless','Scanner Intraoral MEDIT i700 Wireless'),
('etapa_1_scanner','scanner_intraoral','product','Scanner Intraoral MEDIT i900','Scanner Intraoral MEDIT i900'),
('etapa_1_scanner','scanner_intraoral','product','Scanner intraoral BLZ INO 100 Plus','Scanner intraoral BLZ INO 100 Plus'),
('etapa_1_scanner','scanner_intraoral','product','Scanner intraoral BLZ INO 200','Scanner intraoral BLZ INO 200'),
('etapa_1_scanner','scanner_intraoral','product','Scanner intraoral BLZ Leap 500','Scanner intraoral BLZ Leap 500'),
('etapa_1_scanner','scanner_bancada','product','Scanner bancada Medit T100','Scanner bancada Medit T100'),
('etapa_1_scanner','scanner_bancada','product','Scanner Medit T310','Scanner Medit T310'),
('etapa_1_scanner','scanner_bancada','product','Scanner de bancada BLZ LS100','Scanner de bancada BLZ LS100'),
('etapa_1_scanner','acessorios','product','Dispositivo BLZ Dental DMC','Dispositivo BLZ Dental DMC'),
('etapa_1_scanner','acessorios','product','Dispositivo ioConnect TruAbutment','Dispositivo ioConnect TruAbutment'),
('etapa_1_scanner','notebook','product','Notebook','Notebook'),
('etapa_1_scanner','pecas_partes','product','Peças/Partes','Peças/Partes'),

-- Etapa 2 · CAD
('etapa_2_cad','software','product','Softwares CAD exocad DentCad','Softwares CAD exocad DentCad'),
('etapa_2_cad','software','product','Softwares CAD exocad exoplan','Softwares CAD exocad exoplan'),
('etapa_2_cad','software','product','Softwares CAD Medit Clinic App','Softwares CAD Medit Clinic App'),
('etapa_2_cad','software','product','Softwares CAD Blz dental Cad','Softwares CAD Blz dental Cad'),
('etapa_2_cad','creditos_ia','product','Ativação exocad DentalCad I.A.','Ativação exocad DentalCad I.A.'),
('etapa_2_cad','creditos_ia','product','Crédito exocad DentalCad I.A.','Crédito exocad DentalCad I.A.'),
('etapa_2_cad','creditos_ia','product','Crédito BLZ I.A.','Crédito BLZ I.A.'),
('etapa_2_cad','servico','product','Terceirização de projetos CAD','Terceirização de projetos CAD'),

-- Etapa 3 · Impressão 3D
('etapa_3_impressao','resina','product','Resina 3D Smart Print Bio Vitality','Resina 3D Smart Print Bio Vitality'),
('etapa_3_impressao','resina','product','Resina 3D Smart Print Bio Temp','Resina 3D Smart Print Bio Temp'),
('etapa_3_impressao','resina','product','Resina 3D Smart Print Bio Bite Splint','Resina 3D Smart Print Bio Bite Splint'),
('etapa_3_impressao','resina','product','Resina 3D Smart Print Bio Clear Guide','Resina 3D Smart Print Bio Clear Guide'),
('etapa_3_impressao','resina','product','Resina 3D Smart Print Modelo Plus','Resina 3D Smart Print Modelo Plus'),
('etapa_3_impressao','resina','product','Resina 3D Smart Print Modelo Precision','Resina 3D Smart Print Modelo Precision'),
('etapa_3_impressao','resina','product','Resina 3D Smart Print Modelo Láqua','Resina 3D Smart Print Modelo Láqua'),
('etapa_3_impressao','resina','product','Resina 3D Smart Print Bio Vitality Classic','Resina 3D Smart Print Bio Vitality Classic'),
('etapa_3_impressao','resina','product','Resina 3D Smart Print Bio Vitality HT','Resina 3D Smart Print Bio Vitality HT'),
('etapa_3_impressao','resina','product','Resina 3D Smart Print Bio Vitality All-On-X','Resina 3D Smart Print Bio Vitality All-On-X'),
('etapa_3_impressao','resina','product','Resina 3D Smart Print Bio Temp B1','Resina 3D Smart Print Bio Temp B1'),
('etapa_3_impressao','resina','product','Resina 3D Smart Print Bio Bite Splint Clear','Resina 3D Smart Print Bio Bite Splint Clear'),
('etapa_3_impressao','resina','product','Resina 3D Smart Print Bio Bite Splint +Flex','Resina 3D Smart Print Bio Bite Splint +Flex'),
('etapa_3_impressao','resina','product','Resina Smart 3D Print Bio Clear Guide','Resina Smart 3D Print Bio Clear Guide'),
('etapa_3_impressao','resina','product','Resina 3D Smart Print Bio Denture','Resina 3D Smart Print Bio Denture'),
('etapa_3_impressao','resina','product','Resina 3D Smart Print Bio Denture Translúcida','Resina 3D Smart Print Bio Denture Translúcida'),
('etapa_3_impressao','resina','product','Resina 3D Smart Print Bio GOWhite','Resina 3D Smart Print Bio GOWhite'),
('etapa_3_impressao','resina','product','Resina 3d Smart Print Bio Direct Aligner','Resina 3d Smart Print Bio Direct Aligner'),
('etapa_3_impressao','software_imp','product','Software Smart Slicer','Software Smart Slicer'),
('etapa_3_impressao','impressora','product','Impressora 3D Asiga Ultra','Impressora 3D Asiga Ultra'),
('etapa_3_impressao','impressora','product','Impressora 3D Asiga MAX 2','Impressora 3D Asiga MAX 2'),
('etapa_3_impressao','impressora','product','Impressora 3D Rayshape Edge Mini','Impressora 3D Rayshape Edge Mini'),
('etapa_3_impressao','impressora','product','Impressora 3D Miicraft Alpha','Impressora 3D Miicraft Alpha'),
('etapa_3_impressao','impressora','product','Impressora 3D Elegoo Mars 5 Ultra','Impressora 3D Elegoo Mars 5 Ultra'),
('etapa_3_impressao','acessorios','product','Acessórios','Acessórios'),
('etapa_3_impressao','pecas_partes','product','Peças/Partes','Peças/Partes'),

-- Etapa 4 · Pós-Impressão
('etapa_4_pos_impressao','equipamentos','product','Elegoo Wash & Cure Mercury 2-in-1 V2.0','Elegoo Wash & Cure Mercury 2-in-1 V2.0'),
('etapa_4_pos_impressao','equipamentos','product','Equipamento UV ShapeCure D','Equipamento UV ShapeCure D'),
('etapa_4_pos_impressao','equipamentos','product','Equipamento UV Magna Box EDG','Equipamento UV Magna Box EDG'),
('etapa_4_pos_impressao','equipamentos','product','Equipamento Asiga Cure','Equipamento Asiga Cure'),
('etapa_4_pos_impressao','equipamentos','product','Equipamento Pionext UV-02','Equipamento Pionext UV-02'),
('etapa_4_pos_impressao','equipamentos','product','Equipamento Cuba Ultrassônica','Equipamento Cuba Ultrassônica'),
('etapa_4_pos_impressao','equipamentos','product','Equipamento Misturador de Resinas','Equipamento Misturador de Resinas'),
('etapa_4_pos_impressao','limpeza_acabamento','product','Sistema de limpeza NanoClean PoD','Sistema de limpeza NanoClean PoD'),
('etapa_4_pos_impressao','limpeza_acabamento','product','Sistema de limpeza NanoClean (Caneta)','Sistema de limpeza NanoClean (Caneta)'),
('etapa_4_pos_impressao','limpeza_acabamento','product','Sistema de Acabamento GlazeON - Splint','Sistema de Acabamento GlazeON - Splint'),
('etapa_4_pos_impressao','limpeza_acabamento','product','Sistema de limpeza NanoClean Clear','Sistema de limpeza NanoClean Clear'),

-- Etapa 5 · Finalização
('etapa_5_finalizacao','caracterizacao','product','Smart Seal Glaze','Smart Seal Glaze'),
('etapa_5_finalizacao','caracterizacao','product','SmartMake Shade A','SmartMake Shade A'),
('etapa_5_finalizacao','caracterizacao','product','SmartMake Shade B','SmartMake Shade B'),
('etapa_5_finalizacao','caracterizacao','product','SmartMake Shade C','SmartMake Shade C'),
('etapa_5_finalizacao','caracterizacao','product','SmartMake Shade D','SmartMake Shade D'),
('etapa_5_finalizacao','caracterizacao','product','SmartMake Intensivo Brown','SmartMake Intensivo Brown'),
('etapa_5_finalizacao','caracterizacao','product','SmartMake Intensivo Ocre','SmartMake Intensivo Ocre'),
('etapa_5_finalizacao','caracterizacao','product','SmartMake Intensivo Mahogany','SmartMake Intensivo Mahogany'),
('etapa_5_finalizacao','caracterizacao','product','Stains Blue','Stains Blue'),
('etapa_5_finalizacao','caracterizacao','product','Stains Violet','Stains Violet'),
('etapa_5_finalizacao','caracterizacao','product','Stains White','Stains White'),
('etapa_5_finalizacao','caracterizacao','product','Stains Black','Stains Black'),
('etapa_5_finalizacao','caracterizacao','product','SmartBase Clear','SmartBase Clear'),
('etapa_5_finalizacao','caracterizacao','product','SmartMake Efeito Mamelon','SmartMake Efeito Mamelon'),
('etapa_5_finalizacao','caracterizacao','product','SmartWash','SmartWash'),
('etapa_5_finalizacao','caracterizacao','product','SmartGum RED - Intense','SmartGum RED - Intense'),
('etapa_5_finalizacao','caracterizacao','product','SmartGum - PINK','SmartGum - PINK'),
('etapa_5_finalizacao','caracterizacao','product','SmartGum - ORANGE','SmartGum - ORANGE'),
('etapa_5_finalizacao','caracterizacao','product','SmartGum - RUBI','SmartGum - RUBI'),
('etapa_5_finalizacao','caracterizacao','product','SmartGum - CREAM','SmartGum - CREAM'),
('etapa_5_finalizacao','caracterizacao','product','SmartGum - BLACK','SmartGum - BLACK'),
('etapa_5_finalizacao','caracterizacao','product','SmartGum SmartBase Clear','SmartGum SmartBase Clear'),
('etapa_5_finalizacao','caracterizacao','product','SmartGum SmartBase White','SmartGum SmartBase White'),
('etapa_5_finalizacao','caracterizacao','product','KIT Completo SmartGum','KIT Completo SmartGum'),
('etapa_5_finalizacao','caracterizacao','product','KIT Completo SmartMake','KIT Completo SmartMake'),
('etapa_5_finalizacao','instalacao','product','Cimento UNIKK Veneer A1','Cimento UNIKK Veneer A1'),
('etapa_5_finalizacao','instalacao','product','Cimento UNIKK Veneer A2','Cimento UNIKK Veneer A2'),
('etapa_5_finalizacao','instalacao','product','Cimento UNIKK Veneer A3.5','Cimento UNIKK Veneer A3.5'),
('etapa_5_finalizacao','instalacao','product','Cimento UNIKK Veneer B1','Cimento UNIKK Veneer B1'),
('etapa_5_finalizacao','instalacao','product','Cimento UNIKK Veneer BL2','Cimento UNIKK Veneer BL2'),
('etapa_5_finalizacao','instalacao','product','Cimento UNIKK Veneer TRS','Cimento UNIKK Veneer TRS'),
('etapa_5_finalizacao','instalacao','product','Tryin UNIKK A1','Tryin UNIKK A1'),
('etapa_5_finalizacao','instalacao','product','Tryin UNIKK A2','Tryin UNIKK A2'),
('etapa_5_finalizacao','instalacao','product','Tryin UNIKK A3.5','Tryin UNIKK A3.5'),
('etapa_5_finalizacao','instalacao','product','Tryin UNIKK B1','Tryin UNIKK B1'),
('etapa_5_finalizacao','instalacao','product','Tryin UNIKK BL2','Tryin UNIKK BL2'),
('etapa_5_finalizacao','instalacao','product','Tryin UNIKK TRS','Tryin UNIKK TRS'),
('etapa_5_finalizacao','instalacao','product','Kit UNIKK Veneer','Kit UNIKK Veneer'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Direta Atos DA1','Resina Composta Direta Atos DA1'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Direta Atos DA2','Resina Composta Direta Atos DA2'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Direta Atos DA3','Resina Composta Direta Atos DA3'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Direta Atos DA3.5','Resina Composta Direta Atos DA3.5'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Direta Atos DA4','Resina Composta Direta Atos DA4'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Direta Atos EA1','Resina Composta Direta Atos EA1'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Direta Atos EA2','Resina Composta Direta Atos EA2'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Direta Atos EA3','Resina Composta Direta Atos EA3'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Direta Atos EA4','Resina Composta Direta Atos EA4'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Direta Atos XWD','Resina Composta Direta Atos XWD'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Direta Atos XWE','Resina Composta Direta Atos XWE'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Direta Atos WD','Resina Composta Direta Atos WD'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Direta Atos WE','Resina Composta Direta Atos WE'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Direta Atos Clear','Resina Composta Direta Atos Clear'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Direta Atos Opalescente','Resina Composta Direta Atos Opalescente'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Direta Atos Opaco','Resina Composta Direta Atos Opaco'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Direta Atos Unichroma','Resina Composta Direta Atos Unichroma'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Atos Academic Azul Claro','Resina Composta Atos Academic Azul Claro'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Atos Academic Azul Escuro','Resina Composta Atos Academic Azul Escuro'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Atos Academic Branco','Resina Composta Atos Academic Branco'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Atos Academic Verde','Resina Composta Atos Academic Verde'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Atos Academic Vermelho','Resina Composta Atos Academic Vermelho'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Atos Academic Amarelo','Resina Composta Atos Academic Amarelo'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Atos Academic Cinza','Resina Composta Atos Academic Cinza'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Atos Academic Rosa','Resina Composta Atos Academic Rosa'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Atos Academic Laranja','Resina Composta Atos Academic Laranja'),
('etapa_5_finalizacao','dentistica_orto','product','Resina Composta Atos Academic Incolor','Resina Composta Atos Academic Incolor'),
('etapa_5_finalizacao','dentistica_orto','product','Kit Resina Composta Atos Academic - 06 cores','Kit Resina Composta Atos Academic - 06 cores'),
('etapa_5_finalizacao','dentistica_orto','product','Adesivo ortodôntico SmartOrto','Adesivo ortodôntico SmartOrto'),

-- Etapa 6 · Cursos
('etapa_6_cursos','presencial','product','Curso presencial','Curso presencial'),
('etapa_6_cursos','presencial','product','Imersão 3 Dias - Chair Side Print Make','Imersão 3 Dias - Chair Side Print Make'),
('etapa_6_cursos','presencial','product','Imersão clínica','Imersão clínica'),
('etapa_6_cursos','online','product','Acesso Mensal','Acesso Mensal'),
('etapa_6_cursos','online','product','Acesso anual','Acesso anual'),
('etapa_6_cursos','online','product','Cursos Pay-per-view','Cursos Pay-per-view'),

-- Etapa 7 · Fresagem
('etapa_7_fresagem','equipamentos','product','Fresadora Arum 4X-300','Fresadora Arum 4X-300'),
('etapa_7_fresagem','equipamentos','product','Fresadora Arum 5X-300 Pro','Fresadora Arum 5X-300 Pro'),
('etapa_7_fresagem','insumos','product','Blocos de Zircônia Smart Zr (Zirkonzahn)','Blocos de Zircônia Smart Zr (Zirkonzahn)'),
('etapa_7_fresagem','insumos','product','Blocos de Zircônia Smart Zr (Amann)','Blocos de Zircônia Smart Zr (Amann)'),
('etapa_7_fresagem','insumos','product','Blocos de Zircônia Smart Zr HT','Blocos de Zircônia Smart Zr HT'),
('etapa_7_fresagem','insumos','product','Blocos de Zircônia Smart Zr ST','Blocos de Zircônia Smart Zr ST'),
('etapa_7_fresagem','insumos','product','Blocos de Zircônia Smart Zr TT White','Blocos de Zircônia Smart Zr TT White'),
('etapa_7_fresagem','insumos','product','Blocos de Zircônia Smart Zr TT ML','Blocos de Zircônia Smart Zr TT ML'),
('etapa_7_fresagem','insumos','product','Blocos de Zircônia Smart Zr TT GT','Blocos de Zircônia Smart Zr TT GT'),
('etapa_7_fresagem','insumos','product','Berço para Sinterização de Zircônia','Berço para Sinterização de Zircônia'),
('etapa_7_fresagem','insumos','product','Spray Revelador para Escaneamento (uso EXTERNO)','Spray Revelador para Escaneamento (uso EXTERNO)'),
('etapa_7_fresagem','insumos','product','Base para pigmentação de Zircônia 100ml','Base para pigmentação de Zircônia 100ml'),
('etapa_7_fresagem','insumos','product','Base para pigmentação de Zircônia 50ml','Base para pigmentação de Zircônia 50ml'),
('etapa_7_fresagem','insumos','product','Blocos de Dissilicato de Lítio Evolith CAD 14mm','Blocos de Dissilicato de Lítio Evolith CAD 14mm'),
('etapa_7_fresagem','insumos','product','Fresa para Dissilicato de Lítio','Fresa para Dissilicato de Lítio'),
('etapa_7_fresagem','insumos','product','Fresas Smart-DLC para Zircônia','Fresas Smart-DLC para Zircônia'),
('etapa_7_fresagem','insumos','product','Efeitos para Pigmentação de Zircônia 20ml','Efeitos para Pigmentação de Zircônia 20ml'),
('etapa_7_fresagem','software','product','Software Fresagem','Software Fresagem'),
('etapa_7_fresagem','servico','product','Serviço Fresagem','Serviço Fresagem'),
('etapa_7_fresagem','acessorios','product','Acessórios','Acessórios'),
('etapa_7_fresagem','pecas_partes','product','Peças/Partes','Peças/Partes')
ON CONFLICT (workflow_stage, workflow_cell, mapping_type, mapped_value) DO NOTHING;
