CREATE TABLE public.piperun_webhook_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id text NOT NULL,
  lead_id uuid REFERENCES public.lia_attendances(id) ON DELETE SET NULL,
  event_action text,
  stage_id int,
  stage_name text,
  pipeline_id int,
  owner_id int,
  raw_payload jsonb NOT NULL,
  hydrated boolean NOT NULL DEFAULT false,
  outcome text,
  error text,
  received_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT ON public.piperun_webhook_events TO service_role;
GRANT SELECT ON public.piperun_webhook_events TO authenticated;

ALTER TABLE public.piperun_webhook_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "admins read piperun_webhook_events"
  ON public.piperun_webhook_events
  FOR SELECT
  TO authenticated
  USING (public.is_admin(auth.uid()));

CREATE INDEX idx_piperun_webhook_events_deal ON public.piperun_webhook_events (deal_id, received_at DESC);
CREATE INDEX idx_piperun_webhook_events_lead ON public.piperun_webhook_events (lead_id, received_at DESC);
CREATE INDEX idx_piperun_webhook_events_outcome ON public.piperun_webhook_events (outcome, received_at DESC);