ALTER TABLE roi_cards
  ADD COLUMN IF NOT EXISTS cam_time_manual NUMERIC DEFAULT 5,
  ADD COLUMN IF NOT EXISTS cam_time_smart NUMERIC DEFAULT 0.5,
  ADD COLUMN IF NOT EXISTS asb_cam BOOLEAN DEFAULT true;