
-- Camada 2: Inserir 5 entradas em company_kb_texts
-- Embeddings serão gerados via index-embeddings posteriormente

INSERT INTO company_kb_texts (title, category, source_label, content, active)
VALUES
('SPIN Competitive Edge - Pitch e Jornada', 'comercial', 'apostila-spin-competitive-edge',
'PITCH DE VENDAS - Smart Dent Competitive Edge. No cenário odontológico contemporâneo, muitos profissionais ainda se encontram em uma rotina onde a inovação é vista como um luxo. Trabalham com métodos que demandam tempo excessivo e dependência de serviços externos. A confecção de peças protéticas envolve idas e vindas com laboratórios, impactando diretamente o cronograma e a autonomia da clínica. A dor latente: dificuldade em consolidar vantagem competitiva. Dependência de terceiros limita agilidade e controle de qualidade. Ausência de fluxo digital integrado resulta em processos manuais propensos a erros e retrabalhos. Implicações: custos mais altos, margens reduzidas, demora afeta percepção de qualidade, equipe gasta tempo em tarefas repetitivas. A SOLUÇÃO Smart Dent: Rayshape Edge Mini (nivelamento automático, aquecimento de tanque, ShapeWare 2.0 com IA, simplifica fluxo digital, permite delegar processo), Resina Bio Vitality (biocompatibilidade comprovada, estabilidade cromática para coroas definitivas e facetas), NanoClean PoD (elimina 100% do uso de IPA, 35 elementos limpos em 60 segundos). JORNADA SPIN - DESEJO: Autonomia para imprimir restaurações e guias cirúrgicos com precisão. Ricardo Arcas imprime coroas provisórias em 17 minutos. Beatriz Cavalcanti simplificou seu dia com fluxo otimizado pela IA. DOR: Frustração com nivelamento manual complexo, inconsistência da resina, softwares que atrapalham. Dependência de terceiros gera retrabalhos, perda de tempo e custos invisíveis. RESULTADO: Luciana Viana economiza R$ 1.800/mês com Edge Mini. Ricardo Arcas imprime coroas com Bio Vitality em 17 min com 147 MPa. Felipe Montenegro produz guias cirúrgicos internamente. MÉTRICAS: ROI 12 meses, Tempo lab 40min→Digital 15min, Perda de pacientes sem digital 50%, Economia mensal R$1.800, Economia resina 30%, 20 Facetas em 13 min, Curva de aprendizado ZERO.', true),

('SPIN Competitive Edge - FAQs SDR', 'sdr', 'apostila-spin-competitive-edge',
'PERGUNTAS FREQUENTES SDR - Apostila SPIN. 1. Para qual clínica é ideal? Clínicas que buscam autonomia e eficiência na produção de peças protéticas sem ser especialista em impressão 3D. 2. Diferenciais? Simplicidade e integração: Edge Mini (nivelamento automático, ShapeWare 2.0 com IA), Bio Vitality (biocompatibilidade, estabilidade cromática), NanoClean PoD (elimina IPA, 35 elementos em 60s). 3. Comparação com métodos tradicionais? Elimina dependência externa, NanoClean substitui limpeza manual com álcool por banho único de 60s para 35 elementos. 4. Problema resolvido? Dificuldade em consolidar vantagem competitiva por dependência externa. Permite controle interno: entrega rápida, precisa de coroas, facetas, guias. 5. Consequências de não adotar? Custos altos, margens reduzidas, retrabalho 30%, clínica fica para trás. 6. Sinais que precisa? Longos prazos, retrabalhos, tempo excessivo em limpeza com IPA, concorrência mais rápida. 7. Resultados em 12 meses? Pós-processamento 13 min (20 facetas), NanoClean 35 elementos em 60s, economia R$1.800/mês, redução 30% custos, aumento 50% eficiência. 8. Implementação? Análise → Configuração Edge Mini → Treinamento ShapeWare → NanoClean PoD → Acompanhamento. Semanas para operar. 9. ROI? R$1.800/mês economia, satisfação, reputação, centro de excelência. 10. Suporte? Suporte técnico contínuo, treinamento completo, Bio Vitality biocompatível, pós-venda estratégico.', true),

('SPIN Competitive Edge - WhatsApp e Abordagem', 'comercial', 'apostila-spin-competitive-edge',
'TEMPLATE WHATSAPP - SPIN Competitive Edge. Mensagem: VOCÊ QUER IMPRIMIR, OU SER ESPECIALISTA EM IMPRESSÃO 3D. Cansado de falhas? Imprima com precisão e agilidade em minutos. Smart Dent: seu consultório voando! Dr(a). [Nome], de [Cidade]/[Estado], tinha o mesmo problema que você: Perde tempo inserindo suportes manualmente, imprime com medo. Hoje? Zero estresse, processo não depende mais do meu tempo! Você também pode ter: Impressões com zero insegurança, Equipe treinável e autônoma, Mais produtividade clínica, Qualidade de laboratório no consultório. Impacto real: Economia de resina 30%, 20 Facetas em 13 Min, Curva de aprendizado ZERO. Storytelling: Cansado de falhas? Imprima com precisão e agilidade em minutos. Smart Dent: seu consultório voando! Vídeo Principal: https://www.youtube.com/watch?v=viuqJuGxRLU - Impressora 3D RayShape Edgemini Odontologia Digital sem Complicação. Vídeos Edge Mini: https://youtu.be/Zek71F0Zt8Y, https://www.youtube.com/watch?v=HyGSOn6gIsw. Vídeos Bio Vitality: https://www.youtube.com/watch?v=KDpFQsIhyaU, https://www.youtube.com/watch?v=roF7b4GBsJc, https://www.youtube.com/watch?v=pIEKiPGVjhk.', true),

('Edge Mini + Vitality + NanoClean - Regras Anti-Alucinação', 'geral', 'apostila-spin-competitive-edge',
'REGRAS ANTI-ALUCINAÇÃO - 3 Produtos SPIN Competitive Edge. RAYSHAPE EDGE MINI: NUNCA afirmar que realiza escaneamento intraoral, design CAD, fresagem, dispensa resinas 3D, peças não precisam pós-processamento, imprime com materiais não fotopolimerizáveis, é dispositivo para restaurações diretas ou scanner 3D. NUNCA misturar com resinas compostas diretas (Atos), blocos cerômero (ATOS Block), cimentos (UNIKK Veneer), adesivos (ATOS Smart Ortho). SEMPRE exigir arquivo STL/OBJ, resinas 3D 405nm, equipamento lavagem/pós-cura UV. SEMPRE explicar que é impressora 3D que requer resinas fotopolimerizáveis, peças precisam pós-processamento, ShapeWare 2.0 é fatiamento NÃO CAD, tecnologia MSLA cura camadas inteiras. RESINA BIO VITALITY: NUNCA afirmar que é temporária, restaurações diretas, dispensa pós-cura, é fresável, é única biocompatível, compatível com qualquer impressora. NUNCA misturar com IPA baixa pureza, solventes não especificados, resinas de outro fabricante na mesma peça. SEMPRE exigir impressora DLP/LCD aberta, pós-cura UV, cimento adesivo. SEMPRE explicar: definitivas longa duração, 5 ANOS comprovação clínica, ISO 10993, 147 MPa, 59.3% carga, Classic 35% vs HT 45% translucidez (diferença ÓPTICA não mecânica). NANOCLEAN POD: NUNCA afirmar que é material/equipamento de impressão 3D, cimento, adesivo, à base de álcool, inflamável, elimina pós-cura UV, compatível com todas resinas (apenas alta carga inorgânica). NUNCA misturar com IPA, outros solventes, água. SEMPRE exigir peças com resinas alta carga inorgânica, pós-cura UV. SEMPRE explicar: solvente limpeza pós-impressão, substitui IPA, para resinas ALTA CARGA INORGÂNICA, não inflamável, Tecnologia PoD reorganização química superficial.', true),

('Depoimentos Clientes - Prova Social Consolidada', 'comercial', 'apostila-spin-competitive-edge',
'DEPOIMENTOS CURADOS - Apostila SPIN Competitive Edge (30 mais relevantes). Beatriz Cavalcanti (Recife/PE, Dentística): simplificou rotina com fluxo digital otimizado pela IA. Ricardo Arcas (Curitiba/PR, Protesista): imprime coroas provisórias em 17 minutos com ajuste perfeito e 147 MPa. Felipe Montenegro (São Paulo/SP, Implantodontista): produz guias cirúrgicos internamente com precisão e biossegurança. Luciana Viana (BH/MG, Clínico Geral): economiza R$1.800/mês com Edge Mini e nivelamento automático. Marcos André (Florianópolis/SC, TPD): transformou laboratório com fluxo digital completo. Dra. Joyce (São Paulo/SP): 30 anos de odontologia, comprou protocolo digital completo no CIOSPI, protocolo do começo ao fim, não só equipamento. Dr. Guilherme (Jaguaré/ES): sem acesso a laboratórios locais, resolveu com Smartdent (Vitality, Bite Splint +Flex). Dra. Paloma (BA, Implantodontista): suporte e assessoria impecável, entrega pontual. Dr. Mauro: treinamento objetivo e prático, aprenda fazendo. Dr. Igor (João Monlevade/MG): destacou competência do professor Danilo e didática dinâmica. Dr. Marco Rigo (INEPOS): suporte diferenciado, superou expectativas. Dra. Ellen (RJ): sistema chairside completo com scanner e impressora. Dr. Yuri Galvão (Cedro/CE): leva inovação ao interior do Ceará. Dra. Beatriz (Juiz de Fora/MG): Medit pelo custo-benefício e integração. Dr. Rildo Barros: 25 anos experiência, independência laboratorial com chairside. Dr. Laio Venâncio (Brasília/DF): implementou chairside antes do treinamento, suporte diferenciado. Dr. Jonathan (Santo André/SP): curso mais completo que já fez, do CAD à maquiagem final. Dr. Allyson André (Natal/RN): todo reabilitador deve estar atualizado com escaneamento e impressão 3D. Dr. Marcos Mendonça (Itabuna/BA): nota 10 em tecnologia, suporte e padrão de excelência. Bruno (João Pessoa/PB): protesista, passo a passo transformador. Dr. Otávio (Bombinhas/SC): praticidade das resinas Vitality e kits funcionais. Dr. Wesley Henrique (Cacoal/RO): ortodontia+implantodontia+estética, 3 dias aprendeu tudo. Dr. Felipe Dantas (Jaguaribe/CE): Medit i600, fluxo CAD/CAM até impressão final. Dr. Alexandre (Pará de Minas/MG): melhor lugar para iniciar no digital. Dra. Micaela Larissa (SP): implementou na semana seguinte ao curso. Dra. Maíra: diferencial no pós-venda e suporte, primeiro contato com digital.', true)

ON CONFLICT (title, source_label) DO UPDATE SET
  content = EXCLUDED.content,
  category = EXCLUDED.category,
  active = true;
